#!/bin/bash - 
#===============================================================================
#
#          FILE: monitorAP.sh 
# 
#         USAGE:  monitor status of wireless AP
# 
#   DESCRIPTION: 
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

#Check arguments
if [ $# -ne 1 ]; then
    echo 'Usage:'
    echo '    monitorAP.sh wlanDevice'
    echo 'Example:'
    echo '    monitorAP.sh wlan0'
    exit 1
fi

export WLAN_DEV=$1

function showAllAP { 
    iwlist ${WLAN_DEV} scan |grep -iE 'cell|essid|signal'; 
}
export -f showAllAP

watch -n 2 -d bash -c showAllAP
